[package]
name = "openalex"
version = "0.1.0"
edition = "2024"

[dependencies]
bon.workspace = true
thiserror.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
wiremock = "0.6"
